databases:
  - name: inventorymanagementsystemdb
    plan: free
    databaseName: inventorymanagementsystem
    user: mysite

services:
  - type: web
    plan: free
    name: inventorymanagementsystem
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn inventory.wsgi:application --bind 0.0.0.0:$PORT'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventorymanagementsystemdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1