databases:
  - name: inventorymanagementsystemdb
    plan: free
    databaseName: inventorymanagementsystem
    user: mysite

services:
  - type: web
    plan: free
    name: inventorymanagementsystem
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn inventorymanagementsystem.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4